import type { HeatZone } from "@/types";

export const heatMapZones: HeatZone[] = [
  {
    id: "luxury-corridor",
    name: "Luxury Corridor",
    x: 35,
    y: 30,
    radius: 8,
    density: {
      daily: 0.75,
      weekend: 0.92,
      event: 0.88,
    },
    type: "luxury",
    brands: ["Gucci", "Cartier", "Louis Vuitton", "Chanel", "Hermès"],
    avgDwell: 45,
  },
  {
    id: "fashion-avenue",
    name: "Fashion Avenue",
    x: 65,
    y: 30,
    radius: 7,
    density: {
      daily: 0.68,
      weekend: 0.85,
      event: 0.90,
    },
    type: "retail",
    brands: ["Zara", "H&M", "Uniqlo", "Mango", "Massimo Dutti"],
    avgDwell: 35,
  },
  {
    id: "aquarium-atrium",
    name: "Aquarium Atrium",
    x: 50,
    y: 50,
    radius: 10,
    density: {
      daily: 0.90,
      weekend: 0.95,
      event: 0.98,
    },
    type: "entertainment",
    brands: ["Dubai Aquarium", "Underwater Zoo", "VR Park"],
    avgDwell: 60,
  },
  {
    id: "dining-district",
    name: "Dining District",
    x: 25,
    y: 70,
    radius: 6,
    density: {
      daily: 0.55,
      weekend: 0.78,
      event: 0.72,
    },
    type: "dining",
    brands: ["Social House", "Tribes", "The Cheesecake Factory", "P.F. Chang's"],
    avgDwell: 55,
  },
  {
    id: "entertainment-hub",
    name: "Entertainment Hub",
    x: 75,
    y: 70,
    radius: 7,
    density: {
      daily: 0.62,
      weekend: 0.88,
      event: 0.95,
    },
    type: "entertainment",
    brands: ["Ice Rink", "Cinema", "KidZania", "SEGA Republic"],
    avgDwell: 90,
  },
  {
    id: "main-entrance",
    name: "Main Entrance",
    x: 50,
    y: 15,
    radius: 9,
    density: {
      daily: 0.95,
      weekend: 0.98,
      event: 1.0,
    },
    type: "retail",
    brands: ["Apple", "Samsung", "Sony", "Microsoft"],
    avgDwell: 25,
  },
  {
    id: "waterfront-promenade",
    name: "Waterfront Promenade",
    x: 15,
    y: 50,
    radius: 8,
    density: {
      daily: 0.80,
      weekend: 0.90,
      event: 0.94,
    },
    type: "entertainment",
    brands: ["Fountain Views", "Outdoor Dining", "Event Space"],
    avgDwell: 40,
  },
  {
    id: "gold-souk",
    name: "Gold Souk",
    x: 85,
    y: 50,
    radius: 5,
    density: {
      daily: 0.45,
      weekend: 0.65,
      event: 0.55,
    },
    type: "luxury",
    brands: ["Damas", "Joyalukkas", "Malabar Gold", "Pure Gold"],
    avgDwell: 30,
  },
];
